hankache/rakuguide

- perl6intro.adoc
Started reading, and found some minor nits to pick. Hope some of these are useful! :)
> Some minor nit-picks

- perl6intro.adoc
Hi!
I went over the document with the spell checker and fixed the errors I found there. As part of this, I changed some of the function names so they are a little more readable.
Hope this helps!
> Typo fixes and improved method names

- perl6intro.adoc
As discussed on IRC channel #perl6 on freenode.
> Fixed "ne" operator description (now "Not equal")

- perl6intro.adoc
> Use with instead of .defined

- perl6intro.adoc
Don't know if this will throw off the table formatting...
> Qualfiy ops as string ops in a couple places

- perl6intro.adoc
I think I may have messed this commit up. 
What I meant to do was correct some language about values/variables.
But I think I got out of sync when you pulled my last PR and have ended up with this commit reverting my last one. Not sure. Please review and pull if it's good, salvage if you can, or let me know if I need to do it over.
> attempt to correct values/variables language

- perl6intro.adoc
"binded" isn't generally a word, I thought it would be helpful to demonstrate out some other behaviour of bound variables (bidirectionality, rebinding), as well as having the example program output inline like some other places in the document.
> typo?, clarify variable binding

- README.md
- perl6intro.adoc
I inadvertently closed my first pull request, but here is another attempt.  I have made changes to Chapter 1 that I think add to consistence and appearance, and I have made some English usage changes also.
> Suggested changes to Chapter 1

- fr.perl6intro.adoc
- Translated to exceptions (included)
- Small corrections
ETA for the rest ~ one week :)
> French translation updated

- fr.perl6intro.adoc
Done ...
- End Translation
- Misc Corrections
- Swap "sous-programme" with "routine"
Mabe still some typos ... but good to go !
> End of French translation is here.

- fr.perl6intro.adoc
- Add in Running Perl 6 code
- Add in Editors
- Add in Scalars
- Add in Fixed-size array
- Add in Multi-dimentional arrays
- Corrections
- s/mutante/mutatrice
> Filled missing French translations

- perl6intro.adoc
* fix array comparison
* document == as numeric comparison
* use scalar variable for promise
> fix array comparison etc.

- ja.perl6intro.adoc
> Add a missing whitespace

- ja.perl6intro.adoc
Hi.
I have updated Japanese document.
> Add a return value section for jadoc

- ja.perl6intro.adoc
> Add a description of :D and :U in the jadoc

- perl6intro.adoc
I can't fix "In 9.1 you say a class can be given lexical scope, but nothing to tell me why I would want to do so, or compared it with non-lexical scope." 
That needs real knowledge not typing skills.
> Corrections

- ja.perl6intro.adoc
I've just deleted newlines in the introduction paragraph.
> Fix the introduction paragraph in the jadoc

- README.md
- pt.perl6intro.adoc
Hi @hankache! First of all, THANK YOU for creating this very nice tutorial.
I went ahead and created a portuguese translation of it. As requested, it was translated directly against the english version and matches the current HEAD (7985e16).
I updated the README file to contain the new translation (with the pt.perl6intro.com link, which of course doesn't work yet).
Hope it helps :D
> Portuguese translation

- pt.perl6intro.adoc
hey @hankache! I was just reviewing the text in pt.perl6intro.com (looks amazing!) and I found this small typo. This patch fixes it :)
> fix typo in pt translation

- ja.perl6intro.adoc
Same as https://github.com/hankache/perl6intro/commit/56490587c2ea0f80db1b80028c69c3ea6c5ea87b
> Minor fix in the jadoc

- ja.perl6intro.adoc
same as https://github.com/hankache/perl6intro/commit/dd2cbfd83eb7bc21a02b8c0b9e828f7877351a40
> Delete an unnecessary line in the jadoc

- nl.perl6intro.adoc
> Wijzigingen door Wendy

- nl.perl6intro.adoc
> erghrdhfdfhhffh

- nl.perl6intro.adoc
Typo's and several text changes for better Dutch.
> Wendy makes changes

- ja.perl6intro.adoc
Now, the Japanese document is up-to-date :)
> [JA] Update many points

- perl6intro.adoc
Hi, I think that the term "greatest common denominator" is invalid.
> Gcd operator name correction

- es.perl6intro.adoc
Cambiando los valores de la tabla de operadores a valores l´ogicos.
> Valores logicos tabla operadores

- ja.perl6intro.adoc
> [JA] Add a whitespace

- perl6intro.adoc
- clarify the email example breakdown
- add better unicode examples
> [EN] changes to regex

- zh.perl6intro.adoc
> little change to make reading more smoothly

- es.perl6intro.adoc
Updating to the last version: rakudo-star-2017.10
> [ES] Update R* Version

- es.perl6intro.adoc
- perl6intro.adoc
Add Perl 6 Alert URL to the Community section.
> Add Perl 6 Alerts URL

- id.perl6intro.adoc
Hi, 
This is Indonesian translation.
Thanks,
Heince
> ID - Indonesian Translation

- de.perl6intro.adoc
update to use the current Module Management Tool (panda -> zef) in the German dokument
> update to use the current Module Management Tool (panda -> zef)

- es.perl6intro.adoc
- perl6intro.adoc
Update Rakudo-star version in English and Spanish pages
> [EN][ES] Update R*

- ja.perl6intro.adoc
c.f., https://github.com/hankache/rakuguide/compare/73d102...eea302
> [JA] Reflect changes occured in the en version between 73d102 to eea302

- nl.perl6intro.adoc
- perl6intro.adoc
For more in-depth answers to questions.
> Mention StackOverflow raku questions

- fr.perl6intro.adoc
It has been a long time ... But anyway here's an update.
So, more natively : Mise à jour pour la version Française.
Best Regards.
> [FR] Change perl6 to raku, add Native Call, update links

- pt.perl6intro.adoc
Since 2019, the community renamed the language to Raku.
> Renaming the language to Raku

- rakuguide.adoc
overseen in https://github.com/hankache/rakuguide/commit/8a917e05ca761d37e19a8382f48099472dba7a07 ?
> rakuguide.adoc: replace md5_hex() with md5()
