hankache/rakuguide

perl6intro.adoc
Presumably the row for the div operator should have 3 div 2 as an example instead.
=> 3 / 2 appears twice in the operators table

perl6intro.adoc
Using a more verbose link syntax because the regular syntax somehow leaves out the last parenthesis.
=> Fixed Wikipedia Salt hyperlink

perl6intro.adoc
I think there is a small typo in the example. Since the result of the last expression is returned as the result of a method, the constructor would return an Int instead of a Human.
=> Return created object instead of Int value.

fr.perl6intro.adoc, perl6intro.adoc
The original code snippet doesn't work for me (Tested in `Rakudo Star 2015.09`), it would output:
```
===SORRY!=== Error while compiling <unknown file>
Cannot use bind operator with this left-hand side
at <unknown file>:1
```
=> Variable can not be binded to the variable which has already been declared

perl6intro.adoc
i found this a bit confusing and thought maybe it was pointing out that ranges do not include the endpoints, when they do
=> corrected the meaning of a comparison

perl6intro.adoc
The construction "append $thing to the beginning of $other_thing" is
replaced by "prepend $thing to $other_thing."
=> Fixes #25 - Append to beginning -> prepend to

perl6intro.adoc
=> Fix a typo "Perl" to "Perl 6"

ja.perl6intro.adoc
Fix #41 
I have changed the following points.
I changed the title to "Perl6入門", because those who seeking an introduction document always input "Perl6 入門" as their web search query.
"Table of Contents" is generally called "目次" in Japan.
In order to demonstrate how easily perl6 could handle unicode characters, I use "こんにちは世界" instead of "Hello World".
=> Fix ja translation

es.perl6intro.adoc, ja.perl6intro.adoc, perl6intro.adoc
Returning undefined values is likely not what newlings want to do. It
makes little sense to not show best practice right from the start.
=> turn --> Int into --> Int:D

perl6intro.adoc
Installing Rakudo Star manually was a simpler way for me.
Your mileage may vary.
=> Improved instructions about installing on Linux

ja.perl6intro.adoc
same as a887f8754a4fbae56280fce19c0e2323d165965a
=> [JA] p6weekly link typo

perl6intro.adoc
The `+` symbol in `<:L+:N>` doesn't mean multiple `<:L>`s, it means `set union`.
```
$ perl6 -e 'say "hello" ~~ /<:L+:N>/'
｢h｣
```
+ See also
+ https://docs.perl6.org/language/regexes#Unicode_properties
=> [EN] Fix a description of <:L+:N>

perl6intro.adoc
Point out more strongly that in certain cases whitespace matters.
This is to potentially avoid confusion, such as this:
https://irclog.perlgeek.de/perl6/2017-08-23#i_15060522
=> Clarify significance of whitespace

perl6intro.adoc
Fix #131 
I believe this wording is more precise than the previous one.
However, such a mathematical notation (e.g., `[0, 5]`) may confuse Perl6 newbies because it overlaps with the list syntax of Perl6.
=> Use more precise expression for range

es.perl6intro.adoc, perl6intro.adoc
It seems that majority of Perl 6 users prefer the .p6 extension. There
are some posts and discussion about it:
- https://www.reddit.com/r/perl6/comments/812cfa/pl_or_pl6/
- https://github.com/perl6/doc/issues/1807
=> [ES] Change script file extensions to .p6

ja.perl6intro.adoc
This commit also contains:
- [JA] Fix typo (Jpanese version of En -> On in the English doc)
=> [JA] Add MacOS C code compile example for NativeCall

de.perl6intro.adoc
I forgot some changes: I hope now all substitutions of 'panda' -> 'zef' are now done. Also an update of the linux installation section is included.
=> second update to  use the current Module Management Tool (Panda -> Zef)

zh.perl6intro.adoc
补充部分漏译的Infix。
修复adoc排版问题(表格中的++/--，原文也有此错误但看不出来，会在中文/日文排版中有体现)。
修正一处错误的示例代码（使它与原文相同）。
为报错信息添加原文/译文对照。
为部分复杂的示例代码增加翻译。
统一regex的翻译（不予翻译），并修正regexes，它是regex的复数形式，在中文中不必体现。
修正一处错误的符号翻译（'：='应为':='）
修正几处错误的adoc排版（adoc会转义'=>' ，应为\=>，原文也有此错误）
Add some of the missing Infix.
Fix adoc layout problem (++/-- in the table, the original text also has this error but can't see it, it will be reflected in Chinese/Japanese typesetting).
Fix a wrong sample code (make it the same as the original).
Add original/translation control for the error message.
Add translations for some of the more complex sample code.
Unify the translation of regex (not translated), and fix regexes, which is the plural form of regex, which does not have to be reflected in Chinese.
Fix a wrong symbol translation (':=' should be ':=') …
=> Supplemental translation and correction errors

perl6intro.adoc
I just noticed while updating the Dutch version, that there are a number of superstitious parentheses in examples.  Since I was not sure whether these were intentional or not, I decided to put them into a PR.  So, if they were intentional, then please just close.  Otherwise, merge!  :-)
=> Remove superstitious parentheses from examples

perl6intro.adoc
I see no point in pointing out two ways of doing the same at this stage,
especially since the "returns" syntax is considered to be less desirable.
=> Remove mention of "returns" in favour of -->

README.md, bg.rakuguide.adoc, it.rakuguide.adoc, pt.rakuguide.adoc, rakuguide.adoc, ru.rakuguide.adoc, tr.rakuguide.adoc, uk.rakuguide.adoc, zh.rakuguide.adoc
This is a minor change.
* renamed Ukrainian translation to comply with  ISO 639-1
* updated lists of translations where applicable.
=> renamed Ukrainian translation according to ISO 639-1

rakuguide.adoc
This patch updates the code example to work with the latest Digest::MD5 as provided by ```zef install Digest::MD5``` these days
See also https://github.com/grondilu/libdigest-raku/issues/40 and https://github.com/ugexe/zef/issues/558
=> Fix Failing Example Code Digest::MD5
